// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/schema.proto

// Protobuf Java Version: 3.25.0
package com.moviecatalogservice.generatedCode;

public interface TrendingMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrendingMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MovieInfo movies = 1;</code>
   */
  java.util.List<com.moviecatalogservice.generatedCode.MovieInfo> 
      getMoviesList();
  /**
   * <code>repeated .MovieInfo movies = 1;</code>
   */
  com.moviecatalogservice.generatedCode.MovieInfo getMovies(int index);
  /**
   * <code>repeated .MovieInfo movies = 1;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .MovieInfo movies = 1;</code>
   */
  java.util.List<? extends com.moviecatalogservice.generatedCode.MovieInfoOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .MovieInfo movies = 1;</code>
   */
  com.moviecatalogservice.generatedCode.MovieInfoOrBuilder getMoviesOrBuilder(
      int index);
}
