// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/schema.proto

// Protobuf Java Version: 3.25.0
package com.moviecatalogservice.generatedCode;

public final class TrendingMoviesGrpc {
  private TrendingMoviesGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrendingMoviesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrendingMoviesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrendingMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrendingMoviesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026main/java/schema.proto\"\027\n\025TrendingMovi" +
      "esRequest\"4\n\026TrendingMoviesResponse\022\032\n\006m" +
      "ovies\030\001 \003(\0132\n.MovieInfo\",\n\tMovieInfo\022\017\n\007" +
      "movieID\030\001 \001(\t\022\016\n\006rating\030\002 \001(\0052[\n\016Trendin" +
      "gMovies\022I\n\024GetTopTrendingMovies\022\026.Trendi" +
      "ngMoviesRequest\032\027.TrendingMoviesResponse" +
      "\"\000B%\n\rcom.moviecatalogservice.generatedCodeB\022TrendingMoviesGrpcP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TrendingMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TrendingMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrendingMoviesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_TrendingMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TrendingMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrendingMoviesResponse_descriptor,
        new java.lang.String[] { "Movies", });
    internal_static_MovieInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MovieInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieInfo_descriptor,
        new java.lang.String[] { "MovieID", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
