// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/schema.proto

// Protobuf Java Version: 3.25.0
package com.moviecatalogservice.generatedCode;

public interface TrendingMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrendingMoviesRequest)
    com.google.protobuf.MessageOrBuilder {
}
