// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/schema.proto

// Protobuf Java Version: 3.25.0
package com.example.trendingservice.generatedCode;

public interface MovieInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movieID = 1;</code>
   * @return The movieID.
   */
  java.lang.String getMovieID();
  /**
   * <code>string movieID = 1;</code>
   * @return The bytes for movieID.
   */
  com.google.protobuf.ByteString
      getMovieIDBytes();

  /**
   * <code>int32 rating = 2;</code>
   * @return The rating.
   */
  int getRating();
}
